#    cplus = 1
#    csharp = 2
#    java = 3
#    go = 4
#    python = 5
#    php = 6
#    js = 7
#    kotlin = 8
#    objc = 9
language: 2

language_flag : c

#namespace
package_name: Data

#java_only
java_package: com.example.data

#java_only
java_outer_classname: Data

#java_only
java_multiple_files: True

# "SPEED" / "CODE_SIZE" / "LITE_RUNTIME"
optimize_for: SPEED

#c++ only
# True / False
cc_enable_arenas: True

#object-c only
objc_class_prefix: NS

#file_extsion
file_ext: .bytes

#git/svn compare
save_log: True

script_folder: ../Client/script/
bin_folder: ../Client/bin/
proto_folder: ../Client/proto/
log_folder: ../Client/log/