#    cplus = 1
#    csharp = 2
#    java = 3
#    go = 4
#    python = 5
#    php = 6
#    js = 7
#    kotlin = 8
#    objc = 9
client_language: 2
server_language: 1

#namespace
package_name: Data

#java_only
java_package: com.example.data

#java_only
java_outer_classname: Data

#java_only
java_multiple_files: True

# "SPEED" / "CODE_SIZE" / "LITE_RUNTIME"
optimize_for: SPEED

#c++ only
# True / False
cc_enable_arenas: True

#object-c only
objc_class_prefix: NS

#file_extsion
client_file_ext: .bytes
server_file_ext: .bin

#git/svn compare
save_log: True

client_script_folder: ../Client/script/
client_bin_folder: ../Client/bin/
client_proto_folder: ../Client/proto/
client_log_folder: ../Client/log/

server_script_folder: ../Server/script/
server_bin_folder: ../Server/bin/
server_proto_folder: ../Server/proto/
server_log_folder: ../Server/log/